from .auth import router as auth_router
from .pacientes import router as pacientes_router
from .sesiones import router as sesiones_router
from .asistencias import router as asistencias_router
from .paquetes import router as paquetes_router
from .pagos import router as pagos_router
from .alertas import router as alertas_router
from .reportes import router as reportes_router
from .transferencias import router as transferencias_router
from .usuarios import router as usuarios_router
from .consultorios import router as consultorios_router
from .diagnosticos import router as diagnosticos_router
from .tratamientos_paciente import router as tratamiento_paciente_router
from .tipos_terapia import router as tipos_terapia_router
from .notificaciones import router as notificaciones_router
from .gimnasio import router as gimnasio_router
from .pacientes_compartidos import router as pacientes_compartidos_router