"""add_transferencias_table

Revision ID: 770569eb3803
Revises: 
Create Date: 2026-04-28 16:20:28.799938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '770569eb3803'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transferencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('terapeuta_origen_id', sa.Integer(), nullable=False),
    sa.Column('terapeuta_destino_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('fecha_retorno_real', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['terapeuta_destino_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['terapeuta_origen_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transferencias_id'), 'transferencias', ['id'], unique=False)
    op.create_table('transferencia_paciente',
    sa.Column('transferencia_id', sa.Integer(), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['transferencia_id'], ['transferencias.id'], )
    )
    op.drop_table('plantillaconsultorio')
    op.drop_index('ix_historialprecios_paquete', table_name='historialpreciospaquetes')
    op.drop_table('historialpreciospaquetes')
    op.drop_table('configuracion')
    op.drop_table('entregaspaciente')
    op.drop_table('metasconsultorio')
    op.drop_index('ix_alertas_leida', table_name='alertas')
    op.create_index(op.f('ix_alertas_id'), 'alertas', ['id'], unique=False)
    op.add_column('asistencias', sa.Column('paciente_id', sa.Integer(), nullable=True))
    op.add_column('asistencias', sa.Column('hora_registro', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('asistencias', sa.Column('asistio', sa.Boolean(), nullable=True))
    op.drop_constraint('asistencias_pacienteid_fecha_key', 'asistencias', type_='unique')
    op.drop_index('ix_asistencias_fecha', table_name='asistencias')
    op.create_index(op.f('ix_asistencias_id'), 'asistencias', ['id'], unique=False)
    op.create_unique_constraint(None, 'asistencias', ['paciente_id', 'fecha'])
    op.drop_constraint('asistencias_pacienteid_fkey', 'asistencias', type_='foreignkey')
    op.create_foreign_key(None, 'asistencias', 'pacientes', ['paciente_id'], ['id'])
    op.drop_column('asistencias', 'pacienteid')
    op.drop_column('asistencias', 'horaregistro')
    op.create_index(op.f('ix_consultorios_id'), 'consultorios', ['id'], unique=False)
    op.add_column('pacientepaquete', sa.Column('paciente_id', sa.Integer(), nullable=True))
    op.add_column('pacientepaquete', sa.Column('paquete_id', sa.Integer(), nullable=True))
    op.add_column('pacientepaquete', sa.Column('precio_final', sa.Float(), nullable=True))
    op.execute("UPDATE pacientepaquete SET precio_final = 0 WHERE precio_final IS NULL")
    op.alter_column('pacientepaquete', 'precio_final',
                 existing_type=sa.Float(),
                 nullable=False,
                 server_default='0')
    op.add_column('pacientepaquete', sa.Column('sesiones_contratadas', sa.Integer(), nullable=True))
    op.add_column('pacientepaquete', sa.Column('sesiones_usadas', sa.Integer(), nullable=True))
    op.add_column('pacientepaquete', sa.Column('fecha_asignacion', sa.Date(), nullable=True))
    op.add_column('pacientepaquete', sa.Column('fecha_expiracion', sa.Date(), nullable=True))
    op.drop_index('ix_pp_estado_fecha', table_name='pacientepaquete')
    op.create_index(op.f('ix_pacientepaquete_id'), 'pacientepaquete', ['id'], unique=False)
    op.drop_constraint('pacientepaquete_paqueteid_fkey', 'pacientepaquete', type_='foreignkey')
    op.drop_constraint('pacientepaquete_pacienteid_fkey', 'pacientepaquete', type_='foreignkey')
    op.create_foreign_key(None, 'pacientepaquete', 'paquetes', ['paquete_id'], ['id'])
    op.create_foreign_key(None, 'pacientepaquete', 'pacientes', ['paciente_id'], ['id'])
    op.drop_column('pacientepaquete', 'fechaexpiracion')
    op.drop_column('pacientepaquete', 'sesionescontratadas')
    op.drop_column('pacientepaquete', 'preciofinal')
    op.drop_column('pacientepaquete', 'pacienteid')
    op.drop_column('pacientepaquete', 'fechaasignacion')
    op.drop_column('pacientepaquete', 'paqueteid')
    op.drop_column('pacientepaquete', 'sesionesusadas')
    op.alter_column('pacientes', 'consultorioid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_pacientes_id'), 'pacientes', ['id'], unique=False)
    op.alter_column('pagos', 'monto',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_index('ix_pagos_paciente', table_name='pagos')
    op.create_index(op.f('ix_pagos_id'), 'pagos', ['id'], unique=False)
    op.alter_column('paquetes', 'preciooficial',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_paquetes_id'), 'paquetes', ['id'], unique=False)
    op.drop_index('ix_sesiones_fecha', table_name='sesionesterapia')
    op.drop_index('ix_sesiones_fecha_terapeuta', table_name='sesionesterapia')
    op.drop_index('ix_sesiones_paciente', table_name='sesionesterapia')
    op.drop_index('ix_sesiones_terapeuta', table_name='sesionesterapia')
    op.create_index(op.f('ix_sesionesterapia_id'), 'sesionesterapia', ['id'], unique=False)
    op.add_column('sesiontratamiento', sa.Column('sesion_id', sa.Integer(), nullable=True))
    op.add_column('sesiontratamiento', sa.Column('tratamiento_id', sa.Integer(), nullable=True))
    op.add_column('sesiontratamiento', sa.Column('duracion_minutos', sa.Integer(), nullable=True))
    op.drop_constraint('sesiontratamiento_sesionid_tratamientoid_key', 'sesiontratamiento', type_='unique')
    op.create_index(op.f('ix_sesiontratamiento_id'), 'sesiontratamiento', ['id'], unique=False)
    op.drop_constraint('sesiontratamiento_sesionid_fkey', 'sesiontratamiento', type_='foreignkey')
    op.drop_constraint('sesiontratamiento_tratamientoid_fkey', 'sesiontratamiento', type_='foreignkey')
    op.create_foreign_key(None, 'sesiontratamiento', 'tipostratamiento', ['tratamiento_id'], ['id'])
    op.create_foreign_key(None, 'sesiontratamiento', 'sesionesterapia', ['sesion_id'], ['id'])
    op.drop_column('sesiontratamiento', 'tratamientoid')
    op.drop_column('sesiontratamiento', 'duracionminutos')
    op.drop_column('sesiontratamiento', 'sesionid')
    op.create_index(op.f('ix_tipostratamiento_id'), 'tipostratamiento', ['id'], unique=False)
    op.drop_index('ix_usuarios_rol', table_name='usuarios')
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.create_index('ix_usuarios_rol', 'usuarios', ['rol'], unique=False)
    op.drop_index(op.f('ix_tipostratamiento_id'), table_name='tipostratamiento')
    op.add_column('sesiontratamiento', sa.Column('sesionid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sesiontratamiento', sa.Column('duracionminutos', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sesiontratamiento', sa.Column('tratamientoid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sesiontratamiento', type_='foreignkey')
    op.drop_constraint(None, 'sesiontratamiento', type_='foreignkey')
    op.create_foreign_key('sesiontratamiento_tratamientoid_fkey', 'sesiontratamiento', 'tipostratamiento', ['tratamientoid'], ['id'])
    op.create_foreign_key('sesiontratamiento_sesionid_fkey', 'sesiontratamiento', 'sesionesterapia', ['sesionid'], ['id'])
    op.drop_index(op.f('ix_sesiontratamiento_id'), table_name='sesiontratamiento')
    op.create_unique_constraint('sesiontratamiento_sesionid_tratamientoid_key', 'sesiontratamiento', ['sesionid', 'tratamientoid'])
    op.drop_column('sesiontratamiento', 'duracion_minutos')
    op.drop_column('sesiontratamiento', 'tratamiento_id')
    op.drop_column('sesiontratamiento', 'sesion_id')
    op.drop_index(op.f('ix_sesionesterapia_id'), table_name='sesionesterapia')
    op.create_index('ix_sesiones_terapeuta', 'sesionesterapia', ['terapeutaid'], unique=False)
    op.create_index('ix_sesiones_paciente', 'sesionesterapia', ['pacienteid'], unique=False)
    op.create_index('ix_sesiones_fecha_terapeuta', 'sesionesterapia', ['fecha', 'terapeutaid'], unique=False)
    op.create_index('ix_sesiones_fecha', 'sesionesterapia', ['fecha'], unique=False)
    op.drop_index(op.f('ix_paquetes_id'), table_name='paquetes')
    op.alter_column('paquetes', 'preciooficial',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.drop_index(op.f('ix_pagos_id'), table_name='pagos')
    op.create_index('ix_pagos_paciente', 'pagos', ['pacienteid'], unique=False)
    op.alter_column('pagos', 'monto',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_pacientes_id'), table_name='pacientes')
    op.alter_column('pacientes', 'consultorioid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('pacientepaquete', sa.Column('sesionesusadas', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('pacientepaquete', sa.Column('paqueteid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pacientepaquete', sa.Column('fechaasignacion', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=True))
    op.add_column('pacientepaquete', sa.Column('pacienteid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pacientepaquete', sa.Column('preciofinal', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('pacientepaquete', sa.Column('sesionescontratadas', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pacientepaquete', sa.Column('fechaexpiracion', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pacientepaquete', type_='foreignkey')
    op.drop_constraint(None, 'pacientepaquete', type_='foreignkey')
    op.create_foreign_key('pacientepaquete_pacienteid_fkey', 'pacientepaquete', 'pacientes', ['pacienteid'], ['id'])
    op.create_foreign_key('pacientepaquete_paqueteid_fkey', 'pacientepaquete', 'paquetes', ['paqueteid'], ['id'])
    op.drop_index(op.f('ix_pacientepaquete_id'), table_name='pacientepaquete')
    op.create_index('ix_pp_estado_fecha', 'pacientepaquete', ['estado', 'fechaexpiracion'], unique=False)
    op.drop_column('pacientepaquete', 'fecha_expiracion')
    op.drop_column('pacientepaquete', 'fecha_asignacion')
    op.drop_column('pacientepaquete', 'sesiones_usadas')
    op.drop_column('pacientepaquete', 'sesiones_contratadas')
    op.drop_column('pacientepaquete', 'precio_final')
    op.drop_column('pacientepaquete', 'paquete_id')
    op.drop_column('pacientepaquete', 'paciente_id')
    op.drop_index(op.f('ix_consultorios_id'), table_name='consultorios')
    op.add_column('asistencias', sa.Column('horaregistro', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('get_ecuador_time()'), autoincrement=False, nullable=True))
    op.add_column('asistencias', sa.Column('pacienteid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'asistencias', type_='foreignkey')
    op.create_foreign_key('asistencias_pacienteid_fkey', 'asistencias', 'pacientes', ['pacienteid'], ['id'])
    op.drop_constraint(None, 'asistencias', type_='unique')
    op.drop_index(op.f('ix_asistencias_id'), table_name='asistencias')
    op.create_index('ix_asistencias_fecha', 'asistencias', ['fecha'], unique=False)
    op.create_unique_constraint('asistencias_pacienteid_fecha_key', 'asistencias', ['pacienteid', 'fecha'])
    op.drop_column('asistencias', 'asistio')
    op.drop_column('asistencias', 'hora_registro')
    op.drop_column('asistencias', 'paciente_id')
    op.drop_index(op.f('ix_alertas_id'), table_name='alertas')
    op.create_index('ix_alertas_leida', 'alertas', ['leida'], unique=False)
    op.create_table('metasconsultorio',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('consultorioid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('metabasesemanalsesiones', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tasacrecimientoanual', sa.NUMERIC(precision=6, scale=5), server_default=sa.text('0.16'), autoincrement=False, nullable=True),
    sa.Column('fechainicio', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fechafin', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['consultorioid'], ['consultorios.id'], name='metasconsultorio_consultorioid_fkey'),
    sa.PrimaryKeyConstraint('id', name='metasconsultorio_pkey')
    )
    op.create_table('entregaspaciente',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pacienteid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('numeroentrega', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pacienteid'], ['pacientes.id'], name='entregaspaciente_pacienteid_fkey'),
    sa.PrimaryKeyConstraint('id', name='entregaspaciente_pkey')
    )
    op.create_table('configuracion',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preciosesionsuelta', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('25.00'), autoincrement=False, nullable=True),
    sa.Column('ultimaactualizacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('get_ecuador_time()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('id = 1', name='configuracion_id_check'),
    sa.PrimaryKeyConstraint('id', name='configuracion_pkey')
    )
    op.create_table('historialpreciospaquetes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('paqueteid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('precioanterior', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('precionuevo', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('fechacambio', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('get_ecuador_time()'), autoincrement=False, nullable=True),
    sa.Column('usuarioid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('motivo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['paqueteid'], ['paquetes.id'], name='historialpreciospaquetes_paqueteid_fkey'),
    sa.ForeignKeyConstraint(['usuarioid'], ['usuarios.id'], name='historialpreciospaquetes_usuarioid_fkey'),
    sa.PrimaryKeyConstraint('id', name='historialpreciospaquetes_pkey')
    )
    op.create_index('ix_historialprecios_paquete', 'historialpreciospaquetes', ['paqueteid'], unique=False)
    op.create_table('plantillaconsultorio',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('consultorioid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('numeroterapeutas', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fechainicio', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fechafin', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['consultorioid'], ['consultorios.id'], name='plantillaconsultorio_consultorioid_fkey'),
    sa.PrimaryKeyConstraint('id', name='plantillaconsultorio_pkey')
    )
    op.drop_table('transferencia_paciente')
    op.drop_index(op.f('ix_transferencias_id'), table_name='transferencias')
    op.drop_table('transferencias')
    # ### end Alembic commands ###
